CREATE DATABASE EXAM_4
--IDENTITY(1,1) IS EQUAL TO AUTO INCREMENT
CREATE TABLE CARS(
CARS_ID INT IDENTITY(1,1) PRIMARY KEY,
REGISTER_NUMBER VARCHAR(10) UNIQUE NOT NULL, /*CAN BE PRIMARY KEY*/
COMPANY VARCHAR(30) NOT NULL,
MODEL VARCHAR(30) NOT NULL
)

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY,
FNAME VARCHAR(30) NOT NULL,
LNAME VARCHAR(30) NOT NULL,
BIRTH DATE NOT NULL
)

CREATE TABLE RENT_CAR(
EMPLOYEE_ID INT FOREIGN KEY REFERENCES EMPLOYEE ON DELETE CASCADE,
CARS_ID INT FOREIGN KEY REFERENCES CARS ON DELETE CASCADE,
RENT_DATE DATE NOT NULL,
PAYED_SUM INT CHECK(PAYED_SUM > 0)
PRIMARY KEY(EMPLOYEE_ID, CARS_ID, RENT_DATE)
)

ALTER TABLE CARS
ADD COLOR VARCHAR(20) NOT NULL

INSERT INTO CARS(REGISTER_NUMBER, COMPANY, MODEL, COLOR)
VALUES('C456XY', 'TESLA', 'MODEL 3', 'RED')
INSERT INTO EMPLOYEE(FNAME, LNAME, BIRTH)
VALUES('JOHN', 'BROWN', '1990-05-15')
INSERT INTO RENT_CAR(EMPLOYEE_ID, CARS_ID, RENT_DATE, PAYED_SUM)
VALUES(1, 1, '2019-05-10', 200)

UPDATE CARS
SET COLOR = 'GREY'
WHERE COMPANY = 'Mitsubishi'

DELETE FROM RENT_CAR
WHERE RENT_DATE < '2000-10-20'




SELECT NAME
FROM DEPARTMENTS
WHERE STATE = 'Washington'
ORDER BY NAME DESC

SELECT r.NAME, COUNT(c.COUNTRY_ID) as COUNT_COUNTRY
FROM REGIONS r
JOIN COUNTRIES c
ON r.REGION_ID = c.REGION_ID
GROUP BY r.NAME
HAVING COUNT(c.COUNTRY_ID) > 5

SELECT TOP 1 c.FNAME, c.LNAME, SUM(QUANTITY * UNIT_PRICE), co.NAME
FROM CUSTOMERS c
JOIN ORDERS o
ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN ORDER_ITEMS oi
ON o.ORDER_ID = oi.ORDER_ID
JOIN COUNTRIES co
ON c.COUNTRY_ID = co.COUNTRY_ID
GROUP BY c.FNAME, c.LNAME, co.NAME
ORDER BY SUM(QUANTITY * UNIT_PRICE) DESC

SELECT TOP 5 e.FNAME, e.LNAME, COUNT(ORDER_ID) AS TOTAL
FROM EMPLOYEES e
JOIN ORDERS o
ON E.EMPLOYEE_ID = o.EMPLOYEE_ID
GROUP BY e.FNAME, e.LNAME
ORDER BY COUNT(ORDER_ID) DESC

CREATE VIEW VIEW_ORDERS
AS
SELECT c.FNAME, c.LNAME, COUNT(o.ORDER_ID) AS COUNT_ORDERS
FROM CUSTOMERS c
LEFT JOIN ORDERS o
ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.FNAME, c.LNAME

SELECT * FROM VIEW_ORDERS