CREATE DATABASE EXAM_3;

CREATE TABLE USERS(
USER_ID INT PRIMARY KEY,
FNAME VARCHAR(30) NOT NULL,
LNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(45) UNIQUE NOT NULL,
USERNAME VARCHAR(30) UNIQUE NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
START_DATE DATETIME DEFAULT GETDATE(),
);

CREATE TABLE ROLES(
NAME VARCHAR(30) PRIMARY KEY
);

CREATE TABLE USER_ROLE(
USER_ID INT FOREIGN KEY REFERENCES USERS ON DELETE CASCADE,
NAME VARCHAR(30) FOREIGN KEY REFERENCES ROLES ON DELETE CASCADE,
DATE_OF_ROLE DATETIME NOT NULL,
PRIMARY KEY(USER_ID, NAME)
);

ALTER TABLE USERS
ADD PHONE_NUMBER VARCHAR(30)

INSERT INTO USERS(USER_ID, FNAME, LNAME, EMAIL, USERNAME, PASSWORD, START_DATE, PHONE_NUMBER)
VALUES(666, 'PETER', 'PETROVIC', 'TRUMP@USA.COM', 'PETERisTRUMO', 'trumphy123', GETDATE(), '+1097435663')
INSERT INTO ROLES(NAME)
VALUES('PRESIDENT OF THE WORLD')
INSERT INTO USER_ROLE(USER_ID, NAME, DATE_OF_ROLE)
VALUES(666, 'PRESIDENT OF THE WORLD', '01-01-2001')

UPDATE USER_ROLE
SET NAME = 'CONTROL'
WHERE USER_ID = 1

DELETE FROM USERS
WHERE START_DATE > '2016-05-15'





SELECT JOB_TITLE
FROM JOBS
WHERE MIN_SALARY > 7000 AND MAX_SALARY < 15000

SELECT SUM(UNIT_PRICE * QUANTITY)
FROM ORDERS o
JOIN ORDER_ITEMS oi
ON o.ORDER_ID = oi.ORDER_ID
WHERE o.ORDER_DATE > '2000-05-01'

SELECT c.FNAME, c.LNAME, o.ORDER_ID, MIN(o.ORDER_DATE) AS min_date
FROM CUSTOMERS c
JOIN ORDERS o
ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE c.GENDER = 'M'
GROUP BY c.FNAME, c.LNAME, o.ORDER_ID

CREATE VIEW VIEW_DEPARTMENTS
AS
SELECT d.NAME, AVG(e.SALARY) as SALARY_AVG
FROM DEPARTMENTS d
JOIN EMPLOYEES e
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY d.NAME

SELECT * FROM VIEW_DEPARTMENTS