--FIRST TASK--
CREATE DATABASE VIDEO_LIBRARY

use VIDEO_LIBRARY;
CREATE TABLE CLIENTS(
CLIENT_ID INT PRIMARY KEY NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(50) NULL
)

CREATE TABLE MEDIA(
MEDIA_ID CHAR(5) PRIMARY KEY NOT NULL,
TITLE VARCHAR(30) NOT NULL,
CREATED DATETIME NOT NULL
)

CREATE TABLE CLIENTSMEDIA(
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENTS ON DELETE CASCADE NOT NULL,
MEDIA_ID CHAR(5) FOREIGN KEY REFERENCES MEDIA ON DELETE CASCADE NOT NULL,
DATERENT DATETIME NOT NULL,
PRICE DECIMAL(6,2) NULL
PRIMARY KEY(CLIENT_ID, MEDIA_ID)
)
--FIRST TASK END--

--SECOND TASK--
INSERT INTO CLIENTS(CLIENT_ID, FNAME, LNAME, ADDRESS)
VALUES(1, 'Petar', 'Bahamov', 'Bahams')

INSERT INTO MEDIA(MEDIA_ID, TITLE, CREATED)
VALUES(1, 'SCI-FI', 20-02-2000)

INSERT INTO CLIENTSMEDIA(CLIENT_ID, MEDIA_ID, DATERENT, PRICE)
VALUES(1, 1, 01-01-2004, 45)

INSERT INTO CLIENTS(CLIENT_ID, FNAME, LNAME, ADDRESS)
VALUES(2, 'Ivan', 'Mahdi', 'UK')

INSERT INTO MEDIA(MEDIA_ID, TITLE, CREATED)
VALUES(3, 'SCI-FI', 20-02-2221)

INSERT INTO CLIENTSMEDIA(CLIENT_ID, MEDIA_ID, DATERENT, PRICE)
VALUES(2, 1, 01-01-2004, 45)

INSERT INTO CLIENTS(CLIENT_ID, FNAME, LNAME, ADDRESS)
VALUES(1, 'Petar', 'Bahamov', 'Bahams')

INSERT INTO MEDIA(MEDIA_ID, TITLE, CREATED)
VALUES(1, 'SCI-FI', 20-02-2000)

INSERT INTO CLIENTSMEDIA(CLIENT_ID, MEDIA_ID, DATERENT, PRICE)
VALUES(1, 1, 01-01-2004, 45)

INSERT INTO CLIENTS(CLIENT_ID, FNAME, LNAME, ADDRESS)
VALUES(1, 'Petar', 'Bahamov', 'Bahams')

INSERT INTO MEDIA(MEDIA_ID, TITLE, CREATED)
VALUES(1, 'SCI-FI', 20-02-2000)

INSERT INTO CLIENTSMEDIA(CLIENT_ID, MEDIA_ID, DATERENT, PRICE)
VALUES(1, 1, 01-01-2004, 45)

INSERT INTO CLIENTS(CLIENT_ID, FNAME, LNAME, ADDRESS)
VALUES(1, 'Petar', 'Bahamov', 'Bahams')

INSERT INTO MEDIA(MEDIA_ID, TITLE, CREATED)
VALUES(1, 'SCI-FI', 20-02-2000)

INSERT INTO CLIENTSMEDIA(CLIENT_ID, MEDIA_ID, DATERENT, PRICE)
VALUES(1, 1, 01-01-2004, 45)

INSERT INTO CLIENTS(CLIENT_ID, FNAME, LNAME, ADDRESS)
VALUES(1, 'Petar', 'Bahamov', 'Bahams')

INSERT INTO MEDIA(MEDIA_ID, TITLE, CREATED)
VALUES(1, 'SCI-FI', 20-02-2000)

INSERT INTO CLIENTSMEDIA(CLIENT_ID, MEDIA_ID, DATERENT, PRICE)
VALUES(1, 1, 01-01-2004, 45)


--SECOND TASK END--

--THIRD TASK--

DELETE FROM CLIENTS
WHERE FNAME = 'Ivan'

--THIRD TASK END--

--FORTH TASK--

UPDATE CLIENTS
SET ADDRESS = '46 Asenovgrad'
WHERE CLIENT_ID = 1;

--FORTH TASK END--

--FIFTH TASK--

SELECT FNAME, LNAME
FROM CLIENTS

--FIFTH TASK END--

--SIXTH TASK--

SELECT m.TITLE, cl.PRICE
FROM MEDIA m
JOIN CLIENTSMEDIA cl
ON m.MEDIA_ID = cl.MEDIA_ID
WHERE cl.PRICE > 5

--SIXTH TASK END--

--SEVENTH TASK--

SELECT m.TITLE, SUM(cl.PRICE) AS BUDGET_MOVIE
FROM MEDIA m
JOIN CLIENTSMEDIA cl
ON m.MEDIA_ID = cl.MEDIA_ID
GROUP BY m.TITLE
ORDER BY SUM(cl.PRICE)

--SEVENTH TASK END--