/*Изведем имената на служителите и имената на клиентите*/

SELECT FNAME

FROM EMPLOYEES

UNION

SELECT FNAME

FROM CUSTOMERS

SELECT FNAME, LNAME

FROM EMPLOYEES

UNION

SELECT FNAME, LNAME

FROM CUSTOMERS

ORDER BY FNAME

SELECT FNAME, LNAME

FROM EMPLOYEES

UNION

SELECT FNAME, NULL

FROM CUSTOMERS

ORDER BY FNAME

SELECT FNAME, LNAME

FROM EMPLOYEES

UNION

SELECT FNAME, CAST(COUNTRY_ID AS VARCHAR)

FROM CUSTOMERS

ORDER BY FNAME

/*Изведете имената на държавите, в които има клиенти или отдели на фирмата*/

SELECT NAME---------------------------------------------------------------------------------------------------------------------------------

FROM CUSTOMERS C JOIN COUNTRIES CO

ON C.COUNTRY_ID = CO.COUNTRY_ID

UNION

SELECT CO.NAME

FROM DEPARTMENTS D JOIN COUNTRIES CO

ON D.COUNTRY_ID = CO.COUNTRY_ID

/*Изведете номерата, датите и стойността на всички поръчки направени през 2000*/

SELECT O.ORDER_ID, ORDER_DATE, SUM(UNIT_PRICE * QUANTITY) AS TOTAL

FROM ORDERS O JOIN ORDER_ITEMS OI

ON O.ORDER_ID = OI.ORDER_ID

WHERE YEAR(ORDER_DATE) = 2000

GROUP BY O.ORDER_ID, ORDER_DATE

/*Изведете ид-тата, датите и стойността на всяка поръчка, като ако всяка поръчка трябва да бъде платена 7 дни след като е поръчана, изведете и датата, на която трябва да бъде платена */

SELECT O.ORDER_ID, ORDER_DATE,SUM(UNIT_PRICE * QUANTITY) AS TOTAL, DATEADD(DAY, 7, ORDER_DATE) AS PAID_DATE
FROM ORDERS O 
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_ID, ORDER_DATE, DATEADD(DAY, 7, ORDER_DATE)



SELECT O.ORDER_ID, ORDER_DATE, SUM(UNIT_PRICE * QUANTITY) AS TOTAL, DATEADD(DAY, 7,ORDER_DATE) AS PAID_DATE--------------------------------------------------------------

FROM ORDERS O JOIN ORDER_ITEMS OI

ON O.ORDER_ID = OI.ORDER_ID

GROUP BY O.ORDER_ID, ORDER_DATE, DATEADD(DAY, 7,ORDER_DATE)

/*Изведете имената на служителите и броя поръчки, които са обработили. Нека в резултата участват и служителите, които не са обработвали поръчки до момента*/

SELECT FNAME + ' ' + LNAME, COUNT(ORDER_ID) AS TOTAL

FROM EMPLOYEES E LEFT JOIN ORDERS O

ON E.EMPLOYEE_ID = O.EMPLOYEE_ID

GROUP BY FNAME + ' ' + LNAME

/*Изведете малките имена, които принадлежат и на служители и на клиенти*/

SELECT FNAME

FROM EMPLOYEES

INTERSECT

SELECT FNAME

FROM CUSTOMERS

SELECT DISTINCT FNAME

FROM EMPLOYEES

WHERE FNAME = ANY(SELECT FNAME

FROM CUSTOMERS)

SELECT DISTINCT FNAME

FROM EMPLOYEES

WHERE FNAME IN(SELECT FNAME

FROM CUSTOMERS)

SELECT DISTINCT FNAME

FROM EMPLOYEES E

WHERE EXISTS (SELECT *

FROM CUSTOMERS C

WHERE E.FNAME = C.FNAME)

/*Изведете имената на държавите, в които има клиенти и отдели на фирмата*/

SELECT DISTINCT CO.NAME

FROM CUSTOMERS C JOIN COUNTRIES CO

ON C.COUNTRY_ID = CO.COUNTRY_ID

JOIN DEPARTMENTS D

ON CO.COUNTRY_ID = D.COUNTRY_ID

SELECT NAME

FROM CUSTOMERS C JOIN COUNTRIES CO

ON C.COUNTRY_ID = CO.COUNTRY_ID

INTERSECT

SELECT CO.NAME

FROM DEPARTMENTS D JOIN COUNTRIES CO

ON D.COUNTRY_ID = CO.COUNTRY_ID

SELECT COUNTRY_ID

FROM CUSTOMERS

INTERSECT

SELECT COUNTRY_ID

FROM DEPARTMENTS

SELECT DISTINCT NAME

FROM COUNTRIES C

WHERE EXISTS(SELECT 1

FROM CUSTOMERS CU

WHERE C.COUNTRY_ID = CU.COUNTRY_ID)

AND EXISTS (SELECT 1

FROM DEPARTMENTS D

WHERE C.COUNTRY_ID = D.COUNTRY_ID)

/*Изведете малките имена, които принадлежат на служители и не принадлежат на клиенти*/

SELECT FNAME

FROM EMPLOYEES

EXCEPT

SELECT FNAME

FROM CUSTOMERS

SELECT DISTINCT FNAME

FROM EMPLOYEES

WHERE FNAME <> ALL(SELECT FNAME-----------------------------------------------------------------------------------------------------------

FROM CUSTOMERS)

SELECT DISTINCT FNAME

FROM EMPLOYEES

WHERE FNAME NOT IN(SELECT FNAME

FROM CUSTOMERS)

SELECT DISTINCT FNAME

FROM EMPLOYEES E

WHERE NOT EXISTS(SELECT FNAME

FROM CUSTOMERS C

WHERE E.FNAME = C.FNAME)

/*Изведете имената на държавите, в които има клиенти и няма служители*/

SELECT DISTINCT CO.NAME

FROM CUSTOMERS C JOIN COUNTRIES CO

ON C.COUNTRY_ID = CO.COUNTRY_ID

LEFT JOIN DEPARTMENTS D

ON D.COUNTRY_ID = CO.COUNTRY_ID

WHERE D.COUNTRY_ID IS NULL

SELECT DISTINCT NAME

FROM COUNTRIES C

WHERE EXISTS(SELECT 1

FROM CUSTOMERS CU

WHERE CU.COUNTRY_ID = C.COUNTRY_ID)

AND NOT EXISTS(SELECT 1

FROM DEPARTMENTS D

WHERE C.COUNTRY_ID = D.COUNTRY_ID)

/*Изведете имената на служителите, които са назначени последни във фирмата */

SELECT FNAME, LNAME, HIRE_DATE

FROM EMPLOYEES

WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE)

FROM EMPLOYEES)

SELECT TOP 1 WITH TIES FNAME, LNAME, HIRE_DATE

FROM EMPLOYEES

ORDER BY HIRE_DATE DESC

/*Изведете имената на клиентите, които са поръчали най-скъпата и най-евтината поръчка и стойността на съответната поръчка*/

SELECT *

FROM (SELECT TOP 1 FNAME, LNAME, O.ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS TOTAL

				FROM CUSTOMERS C, ORDERS O, ORDER_ITEMS OI

				WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND O.ORDER_ID = OI.ORDER_ID

				GROUP BY FNAME, LNAME, O.ORDER_ID

				ORDER BY 4 DESC) ORD

UNION

SELECT *

FROM (SELECT TOP 1 FNAME, LNAME, O.ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS TOTAL

				FROM CUSTOMERS C, ORDERS O, ORDER_ITEMS OI

				WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND O.ORDER_ID = OI.ORDER_ID

				GROUP BY FNAME, LNAME, O.ORDER_ID

				ORDER BY 4) ORD1


				--OTHER VARIANT--

SELECT *
FROM (SELECT TOP 1 FNAME, LNAME, O.ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS TOTAL
		FROM CUSTOMERS C
		JOIN ORDERS O
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
		JOIN ORDER_ITEMS OI
		ON O.ORDER_ID = OI.ORDER_ID
		GROUP BY FNAME, LNAME, O.ORDER_ID
		ORDER BY 4 DESC) ord
UNION
SELECT *
FROM (SELECT TOP 1 FNAME, LNAME, O.ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS TOTAL
		FROM CUSTOMERS C
		JOIN ORDERS O
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
		JOIN ORDER_ITEMS OI
		ON O.ORDER_ID = OI.ORDER_ID
		GROUP BY FNAME, LNAME, O.ORDER_ID
		ORDER BY 4) ord_one