SELECT FNAME, LNAME, SALARY
FROM EMPLOYEES E
WHERE SALARY > ANY (SELECT AVG(SALARY)
					FROM EMPLOYEES EM
					WHERE E.DEPARTMENT_ID = EM.DEPARTMENT_ID)


SELECT TOP 3 NAME, AVG(UNIT_PRICE) AS AVG_PRICE
FROM PRODUCTS P 
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY NAME
ORDER BY AVG_PRICE DESC




SELECT TOP 1 O.ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS TOTAL
FROM ORDERS O
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_ID
ORDER BY TOTAL DESC

SELECT TOP 1 SUM(UNIT_PRICE * QUANTITY) AS TOTAL
FROM ORDER_ITEMS
GROUP BY ORDER_ID
ORDER BY SUM(UNIT_PRICE * QUANTITY) DESC

SELECT MAX(ORD.TOTAL)
FROM (SELECT ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS TOTAL
		FROM ORDER_ITEMS GROUP BY ORDER_ID) ORD


SELECT AVG(ORD_COUNT.COUNT)
FROM (SELECT E.EMPLOYEE_ID, COUNT(ORDER_ID) AS COUNT
FROM EMPLOYEES E 
JOIN ORDERS O
ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
WHERE DEPARTMENT_ID = 80
GROUP BY E.EMPLOYEE_ID) ORD_COUNT


CREATE VIEW EMPLOYEES_VIEW
AS
SELECT FNAME, LNAME, SALARY/12 AS SALARY, DEPARTMENT_ID
FROM EMPLOYEES

SELECT * 
FROM EMPLOYEES_VIEW
ORDER BY 3 DESC

UPDATE EMPLOYEES_VIEW
SET DEPARTMENT_ID = 90
WHERE FNAME = 'LUIS' AND LNAME = 'POPP'

ALTER VIEW EMPLOYEES_VIEW
AS
SELECT FNAME, LNAME, SALARY/12 AS SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
WITH CHECK OPTION

UPDATE EMPLOYEES_VIEW
SET DEPARTMENT_ID = 90
WHERE FNAME = 'PETER' AND LNAME = 'TUCKER'




CREATE VIEW MANAGER_VIEW 
AS
SELECT FNAME, LNAME, SUM(UNIT_PRICE * QUANTITY) AS TOTAL
FROM EMPLOYEES E
JOIN ORDERS O
ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
WHERE E.EMPLOYEE_ID IN(SELECT DISTINCT MANAGER_ID FROM EMPLOYEES)
GROUP BY E.EMPLOYEE_ID, FNAME, LNAME

SELECT * FROM MANAGER_VIEW



CREATE VIEW JOB_DATES
AS 
SELECT JOB_TITLE, MIN(HIRE_DATE) AS MIN_DATE, MAX(HIRE_DATE) AS MAX_DATE
FROM JOBS J, EMPLOYEES E
WHERE J.JOB_ID = E.JOB_ID
GROUP BY JOB_TITLE

SELECT * FROM JOB_DATES